// <auto-generated />
using System;
using GestAuto.Commercial.Infra;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GestAuto.Commercial.Infra.Migrations
{
    [DbContext(typeof(CommercialDbContext))]
    [Migration("20251209014339_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("commercial")
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GestAuto.Commercial.Domain.Entities.Interaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<DateTime>("InteractionDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("interaction_date");

                    b.Property<Guid>("LeadId")
                        .HasColumnType("uuid")
                        .HasColumnName("lead_id");

                    b.Property<string>("Result")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("result");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("lead_id")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("InteractionDate")
                        .HasDatabaseName("idx_interactions_date");

                    b.HasIndex("LeadId")
                        .HasDatabaseName("idx_interactions_lead");

                    b.HasIndex("Type")
                        .HasDatabaseName("idx_interactions_type");

                    b.HasIndex("lead_id");

                    b.ToTable("interactions", "commercial", t =>
                        {
                            t.Property("lead_id")
                                .HasColumnName("lead_id1");
                        });
                });

            modelBuilder.Entity("GestAuto.Commercial.Domain.Entities.Lead", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("InterestedColor")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("interested_color");

                    b.Property<string>("InterestedModel")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("interested_model");

                    b.Property<string>("InterestedTrim")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("interested_trim");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone");

                    b.Property<Guid>("SalesPersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("sales_person_id");

                    b.Property<string>("Score")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("score");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("SalesPersonId")
                        .HasDatabaseName("idx_leads_sales_person");

                    b.HasIndex("Score")
                        .HasDatabaseName("idx_leads_score");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_leads_status");

                    b.ToTable("leads", "commercial");
                });

            modelBuilder.Entity("GestAuto.Commercial.Domain.Entities.Proposal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal>("DiscountAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("discount_amount");

                    b.Property<Guid?>("DiscountApproverId")
                        .HasColumnType("uuid")
                        .HasColumnName("discount_approver_id");

                    b.Property<string>("DiscountReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("discount_reason");

                    b.Property<decimal?>("DownPayment")
                        .HasColumnType("numeric")
                        .HasColumnName("down_payment");

                    b.Property<int?>("Installments")
                        .HasColumnType("integer")
                        .HasColumnName("installments");

                    b.Property<bool>("IsReadyDelivery")
                        .HasColumnType("boolean")
                        .HasColumnName("is_ready_delivery");

                    b.Property<Guid>("LeadId")
                        .HasColumnType("uuid")
                        .HasColumnName("lead_id");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payment_method");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<decimal>("TradeInValue")
                        .HasColumnType("numeric")
                        .HasColumnName("trade_in_value");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UsedVehicleEvaluationId")
                        .HasColumnType("uuid")
                        .HasColumnName("used_vehicle_evaluation_id");

                    b.Property<string>("VehicleColor")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("vehicle_color");

                    b.Property<string>("VehicleModel")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("vehicle_model");

                    b.Property<decimal>("VehiclePrice")
                        .HasColumnType("numeric")
                        .HasColumnName("vehicle_price");

                    b.Property<string>("VehicleTrim")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("vehicle_trim");

                    b.Property<int>("VehicleYear")
                        .HasColumnType("integer")
                        .HasColumnName("vehicle_year");

                    b.HasKey("Id");

                    b.HasIndex("LeadId")
                        .HasDatabaseName("idx_proposals_lead");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_proposals_status");

                    b.ToTable("proposals", "commercial");
                });

            modelBuilder.Entity("GestAuto.Commercial.Domain.Entities.ProposalItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<bool>("IsOptional")
                        .HasColumnType("boolean")
                        .HasColumnName("is_optional");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric")
                        .HasColumnName("price");

                    b.Property<Guid?>("proposal_id")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("proposal_id")
                        .HasDatabaseName("idx_proposal_items_proposal");

                    b.ToTable("proposal_items", "commercial");
                });

            modelBuilder.Entity("GestAuto.Commercial.Infra.Entities.AuditEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("action");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("entity_name");

                    b.Property<string>("NewValues")
                        .HasColumnType("jsonb")
                        .HasColumnName("new_values");

                    b.Property<string>("OldValues")
                        .HasColumnType("jsonb")
                        .HasColumnName("old_values");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("idx_audit_created");

                    b.HasIndex("EntityName", "EntityId")
                        .HasDatabaseName("idx_audit_entity");

                    b.ToTable("audit_entries", "commercial");
                });

            modelBuilder.Entity("GestAuto.Commercial.Infra.Entities.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Error")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("error");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("event_type");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("idx_outbox_pending")
                        .HasFilter("processed_at IS NULL");

                    b.ToTable("outbox_messages", "commercial");
                });

            modelBuilder.Entity("GestAuto.Commercial.Domain.Entities.Interaction", b =>
                {
                    b.HasOne("GestAuto.Commercial.Domain.Entities.Lead", null)
                        .WithMany("Interactions")
                        .HasForeignKey("lead_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GestAuto.Commercial.Domain.Entities.ProposalItem", b =>
                {
                    b.HasOne("GestAuto.Commercial.Domain.Entities.Proposal", null)
                        .WithMany("Items")
                        .HasForeignKey("proposal_id")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("GestAuto.Commercial.Domain.Entities.Lead", b =>
                {
                    b.Navigation("Interactions");
                });

            modelBuilder.Entity("GestAuto.Commercial.Domain.Entities.Proposal", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
