// <auto-generated />
using System;
using GestAuto.Commercial.Infra;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GestAuto.Commercial.Infra.Migrations
{
    [DbContext(typeof(CommercialDbContext))]
    [Migration("20251230213452_AddEstimatedMonthlyIncomeToLeadQualification")]
    partial class AddEstimatedMonthlyIncomeToLeadQualification
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("commercial")
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GestAuto.Commercial.Domain.Entities.Interaction", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<DateTime>("InteractionDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("interaction_date");

                    b.Property<Guid>("LeadId")
                        .HasColumnType("uuid")
                        .HasColumnName("lead_id");

                    b.Property<string>("Result")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("result");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("InteractionDate")
                        .HasDatabaseName("idx_interactions_date");

                    b.HasIndex("LeadId")
                        .HasDatabaseName("idx_interactions_lead");

                    b.HasIndex("Type")
                        .HasDatabaseName("idx_interactions_type");

                    b.ToTable("interactions", "commercial");
                });

            modelBuilder.Entity("GestAuto.Commercial.Domain.Entities.Lead", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("InterestedColor")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("interested_color");

                    b.Property<string>("InterestedModel")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("interested_model");

                    b.Property<string>("InterestedTrim")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("interested_trim");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone");

                    b.Property<Guid>("SalesPersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("sales_person_id");

                    b.Property<string>("Score")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("score");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("SalesPersonId")
                        .HasDatabaseName("idx_leads_sales_person");

                    b.HasIndex("Score")
                        .HasDatabaseName("idx_leads_score");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_leads_status");

                    b.ToTable("leads", "commercial");
                });

            modelBuilder.Entity("GestAuto.Commercial.Domain.Entities.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeliveryDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("delivery_date");

                    b.Property<DateTime?>("EstimatedDeliveryDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("estimated_delivery_date");

                    b.Property<Guid?>("ExternalId")
                        .HasColumnType("uuid")
                        .HasColumnName("external_id");

                    b.Property<Guid>("LeadId")
                        .HasColumnType("uuid")
                        .HasColumnName("lead_id");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("notes");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("order_number");

                    b.Property<Guid>("ProposalId")
                        .HasColumnType("uuid")
                        .HasColumnName("proposal_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<decimal>("TotalValue")
                        .HasColumnType("numeric")
                        .HasColumnName("total_value");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ExternalId")
                        .IsUnique()
                        .HasDatabaseName("idx_orders_external_id");

                    b.HasIndex("LeadId")
                        .HasDatabaseName("idx_orders_lead");

                    b.HasIndex("OrderNumber")
                        .IsUnique()
                        .HasDatabaseName("idx_orders_number");

                    b.HasIndex("ProposalId")
                        .HasDatabaseName("idx_orders_proposal");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_orders_status");

                    b.ToTable("orders", "commercial");
                });

            modelBuilder.Entity("GestAuto.Commercial.Domain.Entities.PaymentMethodEntity", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_payment_methods_code");

                    b.ToTable("payment_methods", "commercial");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "CASH",
                            CreatedAt = new DateTime(2025, 12, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 1,
                            IsActive = true,
                            Name = "À Vista",
                            UpdatedAt = new DateTime(2025, 12, 29, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            Code = "FINANCING",
                            CreatedAt = new DateTime(2025, 12, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 2,
                            IsActive = true,
                            Name = "Financiamento",
                            UpdatedAt = new DateTime(2025, 12, 29, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            Code = "CONSORTIUM",
                            CreatedAt = new DateTime(2025, 12, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 3,
                            IsActive = true,
                            Name = "Consórcio",
                            UpdatedAt = new DateTime(2025, 12, 29, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 4,
                            Code = "LEASING",
                            CreatedAt = new DateTime(2025, 12, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 4,
                            IsActive = true,
                            Name = "Leasing",
                            UpdatedAt = new DateTime(2025, 12, 29, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("GestAuto.Commercial.Domain.Entities.Proposal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal>("DiscountAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("discount_amount");

                    b.Property<Guid?>("DiscountApproverId")
                        .HasColumnType("uuid")
                        .HasColumnName("discount_approver_id");

                    b.Property<string>("DiscountReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("discount_reason");

                    b.Property<decimal?>("DownPayment")
                        .HasColumnType("numeric")
                        .HasColumnName("down_payment");

                    b.Property<int?>("Installments")
                        .HasColumnType("integer")
                        .HasColumnName("installments");

                    b.Property<bool>("IsReadyDelivery")
                        .HasColumnType("boolean")
                        .HasColumnName("is_ready_delivery");

                    b.Property<Guid>("LeadId")
                        .HasColumnType("uuid")
                        .HasColumnName("lead_id");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payment_method");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<decimal>("TradeInValue")
                        .HasColumnType("numeric")
                        .HasColumnName("trade_in_value");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UsedVehicleEvaluationId")
                        .HasColumnType("uuid")
                        .HasColumnName("used_vehicle_evaluation_id");

                    b.Property<string>("VehicleColor")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("vehicle_color");

                    b.Property<string>("VehicleModel")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("vehicle_model");

                    b.Property<decimal>("VehiclePrice")
                        .HasColumnType("numeric")
                        .HasColumnName("vehicle_price");

                    b.Property<string>("VehicleTrim")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("vehicle_trim");

                    b.Property<int>("VehicleYear")
                        .HasColumnType("integer")
                        .HasColumnName("vehicle_year");

                    b.HasKey("Id");

                    b.HasIndex("LeadId")
                        .HasDatabaseName("idx_proposals_lead");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_proposals_status");

                    b.ToTable("proposals", "commercial");
                });

            modelBuilder.Entity("GestAuto.Commercial.Domain.Entities.ProposalItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<bool>("IsOptional")
                        .HasColumnType("boolean")
                        .HasColumnName("is_optional");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric")
                        .HasColumnName("price");

                    b.Property<Guid?>("proposal_id")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("proposal_id")
                        .HasDatabaseName("idx_proposal_items_proposal");

                    b.ToTable("proposal_items", "commercial");
                });

            modelBuilder.Entity("GestAuto.Commercial.Domain.Entities.TestDrive", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("cancellation_reason");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CustomerFeedback")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("customer_feedback");

                    b.Property<Guid>("LeadId")
                        .HasColumnType("uuid")
                        .HasColumnName("lead_id");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("notes");

                    b.Property<Guid>("SalesPersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("sales_person_id");

                    b.Property<DateTime>("ScheduledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uuid")
                        .HasColumnName("vehicle_id");

                    b.HasKey("Id");

                    b.HasIndex("LeadId")
                        .HasDatabaseName("idx_test_drives_lead");

                    b.HasIndex("SalesPersonId")
                        .HasDatabaseName("idx_test_drives_sales_person");

                    b.HasIndex("ScheduledAt")
                        .HasDatabaseName("idx_test_drives_scheduled");

                    b.HasIndex("VehicleId")
                        .HasDatabaseName("idx_test_drives_vehicle");

                    b.ToTable("test_drives", "commercial");
                });

            modelBuilder.Entity("GestAuto.Commercial.Domain.Entities.UsedVehicleEvaluation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool?>("CustomerAccepted")
                        .HasColumnType("boolean")
                        .HasColumnName("customer_accepted");

                    b.Property<string>("CustomerRejectionReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("customer_rejection_reason");

                    b.Property<decimal?>("EvaluatedValue")
                        .HasColumnType("numeric")
                        .HasColumnName("evaluated_value");

                    b.Property<string>("EvaluationNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("evaluation_notes");

                    b.Property<Guid>("ProposalId")
                        .HasColumnType("uuid")
                        .HasColumnName("proposal_id");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("requested_at");

                    b.Property<Guid>("RequestedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("requested_by");

                    b.Property<DateTime?>("RespondedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("responded_at");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ProposalId")
                        .HasDatabaseName("idx_evaluations_proposal");

                    b.HasIndex("RequestedAt")
                        .HasDatabaseName("idx_evaluations_requested_at");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_evaluations_status");

                    b.ToTable("used_vehicle_evaluations", "commercial");
                });

            modelBuilder.Entity("GestAuto.Commercial.Infra.Entities.AuditEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("action");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("entity_name");

                    b.Property<string>("NewValues")
                        .HasColumnType("jsonb")
                        .HasColumnName("new_values");

                    b.Property<string>("OldValues")
                        .HasColumnType("jsonb")
                        .HasColumnName("old_values");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("user_name");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("idx_audit_created");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_audit_user");

                    b.HasIndex("EntityName", "EntityId")
                        .HasDatabaseName("idx_audit_entity");

                    b.ToTable("audit_entries", "commercial");
                });

            modelBuilder.Entity("GestAuto.Commercial.Infra.Entities.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Error")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("error");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("event_type");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("idx_outbox_pending")
                        .HasFilter("processed_at IS NULL");

                    b.ToTable("outbox_messages", "commercial");
                });

            modelBuilder.Entity("GestAuto.Commercial.Domain.Entities.Interaction", b =>
                {
                    b.HasOne("GestAuto.Commercial.Domain.Entities.Lead", null)
                        .WithMany("Interactions")
                        .HasForeignKey("LeadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_interactions_leads_lead_id");
                });

            modelBuilder.Entity("GestAuto.Commercial.Domain.Entities.Lead", b =>
                {
                    b.OwnsOne("GestAuto.Commercial.Domain.ValueObjects.Qualification", "Qualification", b1 =>
                        {
                            b1.Property<Guid>("LeadId")
                                .HasColumnType("uuid");

                            b1.Property<decimal?>("EstimatedMonthlyIncome")
                                .HasColumnType("numeric")
                                .HasColumnName("estimated_monthly_income");

                            b1.Property<DateTime>("ExpectedPurchaseDate")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("expected_purchase_date");

                            b1.Property<bool>("HasTradeInVehicle")
                                .HasColumnType("boolean")
                                .HasColumnName("has_trade_in_vehicle");

                            b1.Property<bool>("InterestedInTestDrive")
                                .HasColumnType("boolean")
                                .HasColumnName("interested_in_test_drive");

                            b1.Property<string>("Notes")
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("qualification_notes");

                            b1.Property<string>("PaymentMethod")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("payment_method");

                            b1.HasKey("LeadId");

                            b1.ToTable("leads", "commercial");

                            b1.WithOwner()
                                .HasForeignKey("LeadId");

                            b1.OwnsOne("GestAuto.Commercial.Domain.ValueObjects.TradeInVehicle", "TradeInVehicle", b2 =>
                                {
                                    b2.Property<Guid>("QualificationLeadId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("Brand")
                                        .IsRequired()
                                        .HasMaxLength(50)
                                        .HasColumnType("character varying(50)")
                                        .HasColumnName("trade_in_brand");

                                    b2.Property<string>("Color")
                                        .IsRequired()
                                        .HasMaxLength(50)
                                        .HasColumnType("character varying(50)")
                                        .HasColumnName("trade_in_color");

                                    b2.Property<string>("GeneralCondition")
                                        .IsRequired()
                                        .HasMaxLength(50)
                                        .HasColumnType("character varying(50)")
                                        .HasColumnName("trade_in_general_condition");

                                    b2.Property<bool>("HasDealershipServiceHistory")
                                        .HasColumnType("boolean")
                                        .HasColumnName("trade_in_has_dealership_service_history");

                                    b2.Property<string>("LicensePlate")
                                        .IsRequired()
                                        .HasMaxLength(10)
                                        .HasColumnType("character varying(10)")
                                        .HasColumnName("trade_in_license_plate");

                                    b2.Property<int>("Mileage")
                                        .HasColumnType("integer")
                                        .HasColumnName("trade_in_mileage");

                                    b2.Property<string>("Model")
                                        .IsRequired()
                                        .HasMaxLength(100)
                                        .HasColumnType("character varying(100)")
                                        .HasColumnName("trade_in_model");

                                    b2.Property<int>("Year")
                                        .HasColumnType("integer")
                                        .HasColumnName("trade_in_year");

                                    b2.HasKey("QualificationLeadId");

                                    b2.ToTable("leads", "commercial");

                                    b2.WithOwner()
                                        .HasForeignKey("QualificationLeadId");
                                });

                            b1.Navigation("TradeInVehicle");
                        });

                    b.Navigation("Qualification");
                });

            modelBuilder.Entity("GestAuto.Commercial.Domain.Entities.Order", b =>
                {
                    b.HasOne("GestAuto.Commercial.Domain.Entities.Proposal", null)
                        .WithMany()
                        .HasForeignKey("ProposalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("GestAuto.Commercial.Domain.Entities.ProposalItem", b =>
                {
                    b.HasOne("GestAuto.Commercial.Domain.Entities.Proposal", null)
                        .WithMany("Items")
                        .HasForeignKey("proposal_id")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("GestAuto.Commercial.Domain.Entities.TestDrive", b =>
                {
                    b.OwnsOne("GestAuto.Commercial.Domain.ValueObjects.TestDriveChecklist", "Checklist", b1 =>
                        {
                            b1.Property<Guid>("TestDriveId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("FinalMileage")
                                .HasColumnType("numeric")
                                .HasColumnName("checklist_final_mileage");

                            b1.Property<string>("FuelLevel")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("checklist_fuel_level");

                            b1.Property<decimal>("InitialMileage")
                                .HasColumnType("numeric")
                                .HasColumnName("checklist_initial_mileage");

                            b1.Property<string>("VisualObservations")
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)")
                                .HasColumnName("checklist_visual_observations");

                            b1.HasKey("TestDriveId");

                            b1.ToTable("test_drives", "commercial");

                            b1.WithOwner()
                                .HasForeignKey("TestDriveId");
                        });

                    b.Navigation("Checklist");
                });

            modelBuilder.Entity("GestAuto.Commercial.Domain.Entities.UsedVehicleEvaluation", b =>
                {
                    b.OwnsOne("GestAuto.Commercial.Domain.Entities.UsedVehicle", "Vehicle", b1 =>
                        {
                            b1.Property<Guid>("UsedVehicleEvaluationId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Brand")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("vehicle_brand");

                            b1.Property<string>("Color")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("vehicle_color");

                            b1.Property<string>("GeneralCondition")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("vehicle_general_condition");

                            b1.Property<bool>("HasDealershipServiceHistory")
                                .HasColumnType("boolean")
                                .HasColumnName("vehicle_has_dealership_service_history");

                            b1.Property<string>("LicensePlate")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("vehicle_license_plate");

                            b1.Property<int>("Mileage")
                                .HasColumnType("integer")
                                .HasColumnName("vehicle_mileage");

                            b1.Property<string>("Model")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("vehicle_model");

                            b1.Property<int>("Year")
                                .HasColumnType("integer")
                                .HasColumnName("vehicle_year");

                            b1.HasKey("UsedVehicleEvaluationId");

                            b1.ToTable("used_vehicle_evaluations", "commercial");

                            b1.WithOwner()
                                .HasForeignKey("UsedVehicleEvaluationId");
                        });

                    b.Navigation("Vehicle")
                        .IsRequired();
                });

            modelBuilder.Entity("GestAuto.Commercial.Domain.Entities.Lead", b =>
                {
                    b.Navigation("Interactions");
                });

            modelBuilder.Entity("GestAuto.Commercial.Domain.Entities.Proposal", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
