// <auto-generated />
using GestAuto.Commercial.Infra;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace GestAuto.Commercial.Infra.Migrations
{
    [DbContext(typeof(CommercialDbContext))]
    [Migration("20251230191500_FixTestDrivesColumns")]
    public partial class FixTestDrivesColumns
    {
    }
}
