// <auto-generated />
using System;
using GestAuto.Commercial.Infra;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GestAuto.Commercial.Infra.Migrations
{
    [DbContext(typeof(CommercialDbContext))]
    [Migration("20251209105500_UpdateTestDriveEntityWithVehicleAndChecklist")]
    partial class UpdateTestDriveEntityWithVehicleAndChecklist
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            // Additional model configuration would go here...
#pragma warning restore 612, 618
        }
    }
}
